# Generated by Django 4.2.20 on 2025-04-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0003_remove_room_students_roomoccupation_time_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomoccupation',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='roomoccupation',
            name='users',
        ),
        migrations.AddField(
            model_name='room',
            name='students',
            field=models.ManyToManyField(through='official.RoomOccupation', to='official.student'),
        ),
    ]
